name: Build, Test and Push Docker Image

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Pega o código do repositório
      - name: Checkout do código
        uses: actions/checkout@v3

      # 2. Login no Docker Hub (precisa dos secrets configurados)
      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Build da imagem
      - name: Build da imagem
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/minha-app:latest .

      - name: Testar container
        run: |
          docker run -d -p 8080:80 --name test-app ${{ secrets.DOCKERHUB_USERNAME }}/minha-app:latest
          sleep 5
          curl -f http://localhost:8080 || (echo "Teste falhou" && exit 1)
          docker stop test-app
